name: OFFSET
favicon: null
layout_spectrum: 0.35419
typography_spectrum: 0.18231
title: Essai Photo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#82acc4'
    - '#47789c'
    - '#e5e5e3'
    - '#070506'
    - '#c48327'
  brandStrength: 0.8125
  lightness: 0.5373041059356183
  saturation: 0.17882649507373571
  rhythmicContrast: 0.6865442474372685
purpose: []
